language: java
jdk:
- openjdk8
branches:
  only:
  - main
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.gradle"
script: "./gradlew clean build -x test"
before_install:
- openssl aes-256-cbc -K $encrypted_5d95ec7b371e_key -iv $encrypted_5d95ec7b371e_iv
  -in src/main/resources/application-aws.tar.enc -out src/main/resources/application-aws.tar
  -d
- openssl aes-256-cbc -K $encrypted_56b29222f5a0_key -iv $encrypted_56b29222f5a0_iv
  -in src/main/resources/application.tar.enc -out src/main/resources/application.tar
  -d
- tar vxf src/main/resources/application.tar
- tar vxf src/main/resources/application-aws.tar
before_deploy:
- zip -r pick-me-up-server *
- mkdir -p deploy
- mv pick-me-up-server.zip deploy/pick-me-up-server.zip
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: pick-me-up-storage
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  wait-until-deployed: true
  local_dir: deploy
  on:
    repo: produce1886/pick-me-up-server
    branch: main
- provider: codedeploy
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  bucket: pick-me-up-storage
  key: pick-me-up-server.zip
  bundle_type: zip
  application: pick-me-up-server
  deployment_group: pick-me-up-server-deploy
  region: ap-northeast-2
  wait-until-deployed: true
  on:
    repo: produce1886/pick-me-up-server
    branch: main
notifications:
  email:
    recipients:
    - cgc8016@ewhain.net
