name: CI Spring Boot application

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: build onto Gradle
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: decrpt secret file
        run: ./decrypt-aws-secret.sh
        env:
          SECRET_PASSPHRASE: ${{ secrets.SECRET_PASSPHRASE }}

      - name: setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: grant gradlew execute permission
        run: chmod +x ./gradlew

      - name: build gradlew
        run: ./gradlew build
